paths:
  dataset: C:\\Company\\Data_Set\\housing.csv

task:
  type: classification
  target_column: price_class
  labeling:
    source_column: median_house_value
    method: quantile
    q: [0.33, 0.66]           # quantile thresholds
    labels: [low, medium, high]   

